### ISSUE TITLE
Convert the same .wav，But the decode buffer information is inconsistent。

### ISSUE THREAD

**Issue by songbing1990** [AnthumChris/fetch-stream-audio#9]
Hi~ 
I'm try process ourself  .wav audio with the repo, But the decode buffer is not the same as ours。I suspect the audio quality effect the result, but I'm not sure。And thank you for giving us different solutions about decode the large .wav audio。

ours ways： use `AudioContext.decodeAudioData()`

Our result:：
![4FDD76CA-7D28-4269-9AFC-FD62272AA0B7](https://user-images.githubusercontent.com/21302386/71224594-e9f7c700-2310-11ea-9db6-f692eb1a5eb4.png)

The repo results：
![E56A150D-F065-491d-89B7-97115E09E35B](https://user-images.githubusercontent.com/21302386/71224832-80c48380-2311-11ea-8e71-e170f5d7ed31.png)

Test .wav audio：
[MRYJ-20190102-160__mdt_1.zip](https://github.com/AnthumChris/fetch-stream-audio/files/3986379/MRYJ-20190102-160__mdt_1.zip)

**Comment by AnthumChris** [comment]
Hi there.  I can't speak on behalf of the third-party Wav decoder because I didn't write it.  This repo only tested a specific 48,000hz file to exemplify Web Audio API usage.  I should have #4 completed before the year ends, and you're welcome to try using Opus files instead of Wav once that completes.

**Comment by songbing1990** [comment]
Copy that and Thank you. I'm looking forward to it. will keep watching the repo and look for other solutions.
